### ISSUE TITLE
Background is not always rendered

### ISSUE THREAD

**Issue by fmigneault** [Ouranosinc/CanarieAPI#5]
See for example (background missing): 
https://borealweb.nfis.org/ogc-pilot-ems/canarie/

Whereas with the expected background : 
https://pavics.ouranos.ca/canarie/

**Comment by fmigneault** [comment]
@dbyrns maybe you got an idea? not critical though

**Comment by tlvu** [comment]
Because the browser searched for https://borealweb.nfis.org/canarie/static/style.css which do not exist and the background is loaded by that CSS.

This https://borealweb.nfis.org/ogc-pilot-ems/canarie/static/style.css works.

**Comment by fmigneault** [comment]
Not sure if this is still an issue, but I cannot open those old links anymore. 
Not seeing any rendering issues on latest instances deployed. 
Reopen as necessary if still relevant.
