### ISSUE TITLE
Existing already published pavics/canarieapi:0.3.5 docker image overridden

### ISSUE THREAD

**Issue by tlvu** [Ouranosinc/CanarieAPI#8]
@nikola-rados found out the `pavics/canarieapi:0.3.5` docker image he got on his server was not the expected one.

That image was published over 2 years ago and already published image should never be overridden.

I have re-pushed the original image to fix his problem.

Below is the screenshot showing an autobuild has been triggered on that old `0.3.5` tag 16 days ago.

@dbyrns can you ask if any of your team members did this?  Please remind them they should never override already published artifacts.

![2020-07-30-165837_833x704_scrot](https://user-images.githubusercontent.com/11966697/88974086-18b22480-d286-11ea-9484-cd307bbffa26.png)

**Comment by fmigneault** [comment]
Build:
https://hub.docker.com/repository/docker/pavics/canarieapi/builds/464f1611-07ba-4d22-9d4e-e26f8da073de
Shows user "dbyrns"...

All others auto-builds employ "pavics" user.



Francis Charette-Migneault, M. Ing, ing.
Agent de recherche | Développeur de logiciel | Vision et imagerie
Research Agent | Software Developer | Vision and Imagery

CRIM – Centre de recherche informatique de Montréal
101 – 405, avenue Ogilvy, Montréal (Québec) H3N 1M3
514 840-1235 poste 3674
francis.charette-migneault@crim.ca<mailto:Diane.Fortin@crim.ca>

Avis de confidentialité : Ce message peut contenir de l’information légalement privilégiée ou confidentielle. Si vous n’êtes pas le destinataire ou croyez avoir reçu par erreur ce message, nous vous saurions gré d’en aviser l’émetteur et d’en détruire le contenu sans le communiquer à d’autres ou le reproduire.

Confidentiality notice: This communication may contain privileged or confidential information. If you are not the intended recipient or received this communication by error, please notify the sender and delete the message without copying or disclosing it.




________________________________

**Comment by dbyrns** [comment]
It was clearly not intentional and no one would want to do this, you can be sure. The only thing I did was to add an auto-build for branches here : https://hub.docker.com/repository/docker/pavics/canarieapi/builds/edit. The faulty build refer to an invalid source : https://github.com/Ouranosinc/CanarieAPI/tree/55c8918e4f5634543768419f424bd6c8d2b11a1a. Was there a branch named "0.3.5" that could have trigger this build and been removed afterward? I cannot see what else could have caused that.

**Comment by fmigneault** [comment]
That's indeed very weird. Especially that is not even the latest version, and only that one specifically was modified.

**Comment by dbyrns** [comment]
Looking more into the log, I saw on the third line :
`Switched to a new branch '0.3.5'`
So clearly adding the auto-build for branches cause the issue and I'm sorry about that. 
Still not sure why dockerhub pick that "branch" or "tag" to rebuild an image and why the source code is no longer available but I'm pretty sure it should not happens again. I will also be extra cautious in the future if we update the auto-build rules to detect any suspicious builds.
So thank you @tlvu to re-push the original image and I think we can now close the issue.

**Comment by fmigneault** [comment]
Maybe it is caused by the regex?
I see `.*` is used in new rule but all examples and existing ones have extra slashes `/.*/`.
I don't know why it would still match because of the branches/tags selector, but who knows.

**Comment by tlvu** [comment]
Closing this issue after your investigations, thanks.

I don't know what you guys all think but I am feeling very uneasy that it is so easy to override already published docker image, not a single warning whatsoever.  When I re-push the old image, there was no warnings, I didn't have to use '--force' with `docker push` (option `--force` did not even exist).  I wonder if in that bad build logs, it shows some warnings about overriding existing tag/image.

I used to have a lot of trust in repo with "auto build" since it's built by DockerHub so I am sure the binary matches the code.  Image manually pushed by someone could be anything, not necessarily matching the code it claims to match.

Now this trust just evaporate for me since it's so easy to override image originally built by the "auto build" feature.  Someone can enable "auto build" then can still push malicious image after the "auto build" is done.

**Comment by dbyrns** [comment]
I agree, an auto-build should not be able to override an image so easily and same thing for a manual push. I search a little bit and found no way to prevent that. A setting would have been welcomed. 

I'm thninking out loud, once @MatProv finnish the setup to submit PR to birdhouse-deploy when new service images are available, we could include the image hash in a comment above the image tag as reference. We could even add a check in the pavics script that warn if the image hash doesn't fit anymore.

**Comment by tlvu** [comment]
> We could even add a check in the pavics script that warn if the image hash doesn't fit anymore.

With you on this one.  We should probably check if someone has not already solved the same problem.  I can not believe we are the first one to notice this huge security hole.

**Comment by fmigneault** [comment]
> we could include the image hash in a comment above the image tag as reference. We could even add a check in the pavics script that warn if the image hash doesn't fit anymore.

Wouldn't it be easier to simply have a docker tag with the actual hash? Some kind of duplicate of the "version tag" for the corresponding commit hash, but that would ensure specific targeted commit instead of potentially override-able version?
eg: 
```
docker push <some-bird>:<git-commit-hash>
docker push <some-bird>:<matching-version>
```

**Comment by dbyrns** [comment]
Keeping the version image only for conveniance? Because I guess we would start to use exclusively the hash one.
I though about using the hash rather the version, but did not go on because having a compose config full of hash would not be really helpful and there is also images that we don't own that would not benefit of this solution.

Looking for answers, I found nothing but expectations from others and kind of workaround involving validation scripts.
See: https://stackoverflow.com/questions/31605661/how-to-prevent-docker-images-on-docker-hub-from-being-overwritten
Or: https://github.com/docker/hub-feedback/issues/958

**Comment by tlvu** [comment]
Go up-vote https://github.com/docker/hub-feedback/issues/958 that @dbyrns found.  Hopefully it will get it moving.

**Comment by fmigneault** [comment]
Considering how long that issue has been opened, that other services offer this feature already, and the recently updated retention policy released few days ago that indicates free DockerHub accounts will soon start to only preserve images push/pulled within the last 6 months, my guess is that they are sadly not going to provide this feature any time soon, or ever.
